# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [4]:
import numpy as np
a=6* np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [38]:
x=9 * np.ones((8,8))
x[1::2,::2] = 3
x[::2,1::2] = 3
print(x)

[[9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [43]:
x=np.empty((3,4))
print(x)
y=6 * np.ones((3,3))
print(y)

[[1.30928180e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.08607623e-042 2.46323871e+184 4.71284398e-062]
 [2.98602648e-032 4.54778471e+174 8.30137038e-067 2.21499990e+160]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [49]:
x=np.array([0,12,45.21,34,99.9])
x=(x-32) * 5/9
print(x)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72222222]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [60]:
x=np.array([1.00000000+0.j , 0.70710678+0.70710678j])
print("Real part of the array")
print(x.real)
print("Imaginary part of the array")
print(x.imag)

Real part of the array
[1.         0.70710678]
Imaginary part of the array
[0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [81]:
x=np.array([0,10,20,40,60])
y=np.array([0,40])
z=[]
for i in x:
    if i in y:
        z.append(True)
    else:
        z.append(False)
        
z=np.array(z)   
print(z)


[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [82]:
x=np.array([0,10,20,40,60])
y=np.array([10,30,40])
z=[]
for i in x:
    if i in y:
        z.append(i)
z=np.array(z)   
print(z) 

[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [90]:
x=np.array([10,10,20,20,30,30])
y=np.array([[1,1],[2,3]])
z=[]
w=[]
for i in x:
    if i not in z:
        z.append(i)
        
for j in np.nditer(y):
    if j not in w:
        w.append(j)
        
z=np.array(z)
print(z)

w=np.array(w)
print(w)
    
    

[10 20 30]
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [98]:
x=np.array([0,10,20,40,60,80])
y=np.array([10,30,40,50,70])
z=[]

for i in x:
    if i not in y:
        z.append(i)
        
for j in y:
    if j not in x:
        z.append(j)
z=np.array(z)
print(np.sort(z))


[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [55]:
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [56]:
import numpy as np
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))

False
True
True
True


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [54]:
x=np.array([1,2,3,4])
z=[]
for i in range(len(x)-1):
    for i in  x:
        z.append(i)
z=np.array(z)
print(z)
        
    
print("2 times",np.tile(x,2))
    
print("3 times",np.tile(x,3))
        

[1 2 3 4 1 2 3 4 1 2 3 4]
2 times [1 2 3 4 1 2 3 4]
3 times [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [31]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

        


    


Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [33]:
a=np.array([1,2])
b=np.array([4,5])

print(a > b)
print(a >= b)
print(a < b)
print(a <= b)


[False False]
[False False]
[ True  True]
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [41]:
x=np.array([[4,6],[2,1]])
a=np.sort(x,axis=0)
print(a)
b=np.sort(a,axis=1)
print(b)

[[2 1]
 [4 6]]
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [60]:
first_names =    ['Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis']
last_names = ['Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl']
x = np.lexsort((first_names, last_names))
print(x)


[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [49]:
x=np.array([[0,10,20],[20,30,40]])
z=[]
for i in np.nditer(x):
    if i > 10:
        z.append(i)
z=np.array(z)    
print("Values bigger than 10 = ",z)
print("Thier indices are ",np.nonzero(x>10))
        

Values bigger than 10 =  [20 20 30 40]
Thier indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [58]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))


128 bytes


## Great Job!